name: tiles_markdown_wysiwyg
version: 0.1.1
author: Jakuub Uhrik <jakuub@mail.com>
description: Small library with implementation of TinyMCE as a component for tiles with minimal implementation.
homepage: https://github.com/jakuub/tiles_markdown_wysiwyg_component
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  markdown: any
  tiles: '>=0.1.3+4'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
