name: tiles_markdown_wysiwyg
version: 0.0.1
description: A starting point for Dart libraries or applications.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  markdown: any
  tiles: '>=0.1.3+4'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
